version: "3"
services:
    flask:
        container_name: flask
        build: *****
        volumes:
            - *****
        ports:
            - *****
        environment:
            - FLASK_DEBUG=1
            - FLASK_ENV=development
            - FLASK_APP=flaskr
        tty: true
        links:
            - *****

    database:
        image: mysql:5.7
        container_name: database
        platform: linux/x86_64
        environment:
            MYSQL_ROOT_PASSWORD: *****
            MYSQL_DATABASE: *****
            MYSQL_USER: *****
            MYSQL_PASSWORD: *****
            TZ: 'Asia/Tokyo'
        volumes:
            - *****:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306

    phpmyadmin:
        container_name: test_phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOSTS=database
            - PMA_USER=light
            - PMA_PASSWORD=light
        ports:
            - 8000:80
