version: "3"
services:
    # バックエンド
    flask:
        container_name: flask
        build: ./flask
        volumes:
            - ./flask:/flask
        ports:
            - "3000:3000"
        # command: flask run --host 0.0.0.0 --port 5000
        environment:
            - FLASK_DEBUG=1
            - FLASK_ENV=development
            - FLASK_APP=flaskr
        tty: true
        # privileged: true
        links:
            - database
    # データベース
    database:
        # build: ./database
        image: mysql:5.7
        container_name: database
        platform: linux/x86_64
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
            MYSQL_USER: light
            MYSQL_PASSWORD: light
            TZ: 'Asia/Tokyo'
        volumes:
            - ./database/sqls:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306

    phpmyadmin:
        container_name: test_phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOSTS=database
            - PMA_USER=light
            - PMA_PASSWORD=light
        ports:
            - 8000:80
